-- MySQL Script generated by MySQL Workbench
-- Tue Sep  3 15:08:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET GLOBAL cte_max_recursion_depth = 20000;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fungoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fungoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fungoDB` DEFAULT CHARACTER SET utf8 ;
USE `fungoDB` ;

-- -----------------------------------------------------
-- Table `fungoDB`.`Autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`autores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nomeautor_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fungoDB`.`UnidadesTaxonomicas`registrofungos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`UnidadesTaxonomicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `unidadeTaxonomicaanterior_id` INT,
  PRIMARY KEY (`id`),
  INDEX `fk_unidadesTaxonomicas_unidadesTaxonomicas1_idx` (`unidadeTaxonomicaanterior_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fungoDB`.`Taxons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`Taxons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) UNIQUE NOT NULL,
  `autor_id` INT NOT NULL,
  `unidadesTaxonomicas_id` INT NOT NULL,
  `taxonanterior_id` INT NOT NULL,
  PRIMARY KEY (`id`, `autor_id`, `unidadesTaxonomicas_id`, `taxonanterior_id`),
  INDEX `fk_taxons_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_taxons_unidadesTaxonomicas1_idx` (`unidadesTaxonomicas_id` ASC) VISIBLE,
  INDEX `fk_taxons_taxons1_idx` (`taxonanterior_id` ASC) VISIBLE,
  CONSTRAINT `fk_taxons_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `fungoDB`.`Autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taxons_unidadesTaxonomicas1`
    FOREIGN KEY (`unidadesTaxonomicas_id`)
    REFERENCES `fungoDB`.`UnidadesTaxonomicas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taxons_taxons1`
    FOREIGN KEY (`taxonanterior_id`)
    REFERENCES `fungoDB`.`Taxons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fungoDB`.`RegistroFungos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`RegistroFungos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `coordenada` VARCHAR(200) NOT NULL,
  `observacoes`TEXT NULL,
  `autor_id` INT NOT NULL,
  `Taxons_id` INT NOT NULL,
  PRIMARY KEY (`id`, `autor_id`, `Taxons_id`),
  INDEX `fk_RegistroFungos_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_RegistroFungos_Taxons1_idx` (`Taxons_id` ASC) VISIBLE,
  CONSTRAINT `fk_RegistroFungos_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `fungoDB`.`Autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroFungos_Taxons1`
    FOREIGN KEY (`Taxons_id`)
    REFERENCES `fungoDB`.`Taxons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fungoDB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL,
  `ultimonome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `autor_id` INT NOT NULL,
  `permissoes` ENUM('user', 'admin') NOT NULL,
  PRIMARY KEY (`id`, `autor_id`),
  INDEX `fk_Users_autor1_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `fungoDB`.`Autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fungoDB`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`Fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `autor_id` INT NOT NULL,
  `RegistroFungos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `autor_id`, `RegistroFungos_id`),
  INDEX `fk_Fotos_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_Fotos_RegistroFungos1_idx` (`RegistroFungos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `fungoDB`.`Autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fotos_RegistroFungos1`
    FOREIGN KEY (`RegistroFungos_id`)
    REFERENCES `fungoDB`.`RegistroFungos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fungoDB`.`Caixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`Caixas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fungoDB`.`Coletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fungoDB`.`Coletas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `substrato` VARCHAR(45) NULL,
  `esporada` VARCHAR(45) NULL,
  `textura` VARCHAR(45) NULL,
  `observacoes`TEXT NULL,
  `autor_id` INT NOT NULL,
  `RegistroFungos_id` INT NOT NULL,
  `Taxons_id` INT NOT NULL,
  `Caixas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `autor_id`, `Taxons_id`, `Caixas_id`),
  INDEX `fk_coleta_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_Coletas_RegistroFungos1_idx` (`RegistroFungos_id` ASC) VISIBLE,
  INDEX `fk_Coletas_Taxons1_idx` (`Taxons_id` ASC) VISIBLE,
  INDEX `fk_Coletas_Caixas1_idx` (`Caixas_id` ASC) VISIBLE,
  CONSTRAINT `fk_coleta_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `fungoDB`.`Autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coletas_RegistroFungos1`
    FOREIGN KEY (`RegistroFungos_id`)
    REFERENCES `fungoDB`.`RegistroFungos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coletas_Taxons1`
    FOREIGN KEY (`Taxons_id`)
    REFERENCES `fungoDB`.`Taxons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coletas_Caixas1`
    FOREIGN KEY (`Caixas_id`)
    REFERENCES `fungoDB`.`Caixas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO unidadestaxonomicas (nome, unidadeTaxonomicaanterior_id) VALUES
('Vida', 0);
-- unidades taxonômicas
INSERT INTO unidadestaxonomicas (nome, unidadeTaxonomicaanterior_id) VALUES
('Domínio', 1),    -- Supondo que "Vida" já foi inserido como a unidade taxonômica de ID 1.
('Reino', 2),      -- "Domínio" já foi inserido como ID 2.
('Subrreino', 3),	--
('Filo', 4),       -- "Reino" está como ID 3.
('Subfilo', 5),    -- "Filo" está como ID 4.
('Classe', 6),     -- "Subfilo" está como ID 5.
('Subclasse', 7),
('Ordem', 8),      -- "Classe" está como ID 6.
('Família', 9),    -- "Ordem" está como ID 7.
('Gênero', 10),     -- "Família" está como ID 8.
('Espécie', 11);    -- "Gênero" está como ID 9.

insert into autores (nome) VALUES
('sem_autor');

-- dominios

INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(1, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Domínio'), 'Eukarya', 1);

-- reino

INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(2, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Reino'), 'Fungi incertae sedis', 1),
(2, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Reino'), 'Líquen incertae sedis', 1),
(2, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Reino'), 'Fungi', 1);

-- subrreinos -myceta

SET @fungi_id = (SELECT id FROM Taxons WHERE nome='Fungi');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) 
VALUES
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Rozellomyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Aphelidiomyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Blastocladiomyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Chytridiomyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Olpidiomyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Basidiobolomyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Zoopagomyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Mucoromyceta', 1),
(@fungi_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subrreino'), 'Dikarya', 1);

-- filos -mycota

SET @rozellomyceta_id = (SELECT id FROM Taxons WHERE nome='Rozellomyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@rozellomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Rozellomycota', 1);

SET @aphelidiomyceta_id = (SELECT id FROM Taxons WHERE nome='Aphelidiomyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@aphelidiomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Aphelidiomycota', 1);

SET @chytridiomyceta_id = (SELECT id FROM Taxons WHERE nome='Chytridiomyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@chytridiomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Neocallimastigomycota', 1),
(@chytridiomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Monoblepharomycota', 1),
(@chytridiomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Chytridiomycota', 1);

SET @blastocladiomyceta_id = (SELECT id FROM Taxons WHERE nome='Blastocladiomyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@blastocladiomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Blastocladiomycota', 1);

SET @basidiobolomyceta_id = (SELECT id FROM Taxons WHERE nome='Basidiobolomyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@basidiobolomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Basidiobolomycota', 1);

SET @olpidiomyceta_id = (SELECT id FROM Taxons WHERE nome='Olpidiomyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@olpidiomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Olpidiomycota', 1);


SET @zoopagomyceta_id = (SELECT id FROM Taxons WHERE nome='Zoopagomyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@zoopagomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Entomophthoromycota', 1),
(@zoopagomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Zoopagomycota', 1),
(@zoopagomyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Kickxellomycota', 1);

SET @mucoromyceta_id = (SELECT id FROM Taxons WHERE nome='Mucoromyceta');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@mucoromyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Mortierellomycota', 1),
(@mucoromyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Calcarisporiellomycota', 1),
(@mucoromyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Mucoromycota', 1),
(@mucoromyceta_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Glomeromycota', 1);

SET @dikarya_id = (SELECT id FROM Taxons WHERE nome='Dikarya');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@dikarya_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Ascomycota', 1),
(@dikarya_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Entorrhizomycota', 1),
(@dikarya_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Filo'), 'Basidiomycota', 1);

-- Subfilos dikarya

SET @ascomycota_id = (SELECT id FROM Taxons WHERE nome='Ascomycota');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@dikarya_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subfilo'), 'Taphrinomycotina', 1),
(@dikarya_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subfilo'), 'Saccharomycotina', 1),
(@dikarya_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subfilo'), 'Pezizomycotina', 1);

SET @basidiomycota_id = (SELECT id FROM Taxons WHERE nome='Basidiomycota');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@basidiomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subfilo'), 'Pucciniomycotina', 1),
(@basidiomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subfilo'), 'Ustilaginomycotina', 1),
(@basidiomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subfilo'), 'Agaricomycotina', 1);

-- Classes Acomycota

SET @Taphrinomycotina_id = (SELECT id FROM Taxons WHERE nome='Taphrinomycotina');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Taphrinomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Neolectomycetes', 1),
(@Taphrinomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Pneumocystidomycetes', 1),
(@Taphrinomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Schizosaccharomycetes', 1),
(@Taphrinomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Taphrinomycetes', 1);

SET @Saccharomycetes_id = (SELECT id FROM Taxons WHERE nome='Saccharomycotina');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Saccharomycetes', 1);

SET @Pezizomycotina_id = (SELECT id FROM Taxons WHERE nome='Pezizomycotina');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Orbiliomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Pezizomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Dothideomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Arthoniomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Eurotiomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Laboulbeniomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Lichinomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Lecanoromycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Leotiomycetes', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Sordariomycetes', 1);

-- subclasses Ascomycota

SET @Dothideomycetes_id = (SELECT id FROM Taxons WHERE nome='Dothideomycetes');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Dothideomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Dothideomycetidae', 1),
(@Dothideomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Pleosporomycetidae', 1);

SET @Eurotiomycetes_id = (SELECT id FROM Taxons WHERE nome='Eurotiomycetes');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Eurotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Chaetothyriomycetidae', 1),
(@Eurotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Mycocaliciomycetidae', 1),
(@Eurotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Eurotiomycetidae', 1);

SET @Lecanoromycetes_id = (SELECT id FROM Taxons WHERE nome='Lecanoromycetes');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Lecanoromycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Acarosporomycetidae', 1),
(@Lecanoromycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Lecanoromycetidae', 1),
(@Lecanoromycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Ostropomycetidae', 1);

SET @Sordariomycetes_id = (SELECT id FROM Taxons WHERE nome='Sordariomycetes');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Xylariomycetidae', 1),
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Hypocreomycetidae', 1),
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Sordariomycetidae', 1);

-- ordens ascomycota
SET @Neolectomycetes_id = (SELECT id FROM Taxons WHERE nome='Neolectomycetes');
SET @Pneumocystidomycetes_id = (SELECT id FROM Taxons WHERE nome='Pneumocystidomycetes');
SET @Schizosaccharomycetes_id = (SELECT id FROM Taxons WHERE nome='Schizosaccharomycetes');
SET @Taphrinomycetes_id = (SELECT id FROM Taxons WHERE nome='Taphrinomycetes');
SET @Saccharomycetes_id = (SELECT id FROM Taxons WHERE nome='Saccharomycetes');
SET @Orbiliomycetes_id = (SELECT id FROM Taxons WHERE nome='Orbiliomycetes');
SET @Pezizomycetes_id = (SELECT id FROM Taxons WHERE nome='Pezizomycetes');
SET @Pezizomycotina_id = (SELECT id FROM Taxons WHERE nome='Pezizomycotina');
SET @Dothideomycetes_id = (SELECT id FROM Taxons WHERE nome='Dothideomycetes');
SET @Dothideomycetidae_id = (SELECT id FROM Taxons WHERE nome='Dothideomycetidae');
SET @Pleosporomycetidae_id = (SELECT id FROM Taxons WHERE nome='Pleosporomycetidae');
SET @Arthoniomycetes_id = (SELECT id FROM Taxons WHERE nome='Arthoniomycetes');
SET @Chaetothyriomycetidae_id = (SELECT id FROM Taxons WHERE nome='Chaetothyriomycetidae');
SET @Mycocaliciomycetidae_id = (SELECT id FROM Taxons WHERE nome='Mycocaliciomycetidae');
SET @Eurotiomycetidae_id = (SELECT id FROM Taxons WHERE nome='Eurotiomycetidae');
SET @Laboulbeniomycetes_id = (SELECT id FROM Taxons WHERE nome='Laboulbeniomycetes');
SET @Lichinomycetes_id = (SELECT id FROM Taxons WHERE nome='Lichinomycetes');
SET @Acarosporomycetidae_id = (SELECT id FROM Taxons WHERE nome='Acarosporomycetidae');
SET @Lecanoromycetes_id = (SELECT id FROM Taxons WHERE nome='Lecanoromycetes');
SET @Lecanoromycetidae_id = (SELECT id FROM Taxons WHERE nome='Lecanoromycetidae');


INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Neolectomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Neolectales', 1),
(@Pneumocystidomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pneumocystidales', 1),
(@Schizosaccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Schizosaccharomycetales', 1),
(@Taphrinomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Taphrinales', 1),
(@Saccharomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Saccharomycetales', 1),
(@Orbiliomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Orbiliales', 1),
(@Pezizomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pezizales', 1),
(@Pezizomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Lahmiales', 1),
(@Pezizomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Medeolariales', 1),
(@Pezizomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Triblidiales', 1),
(@Dothideomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Caprodiales', 1),
(@Dothideomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Dothideales', 1),
(@Dothideomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Myriangiales', 1),
(@Pleosporomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pleosporales', 1),
(@Dothideomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Boltryosphaeriales', 1),
(@Dothideomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Hysteriales', 1),
(@Dothideomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Patellariales', 1),
(@Dothideomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Jahnulales', 1),
(@Arthoniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Arthoniales', 1),
(@Chaetothyriomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Chaetothyriales', 1),
(@Chaetothyriomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pyrenulales', 1),
(@Chaetothyriomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Verrucariales', 1),
(@Mycocaliciomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Mycocaliciales', 1),
(@Eurotiomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Eurotiales', 1),
(@Eurotiomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Onygenales', 1),
(@Eurotiomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Coryneliales', 1),
(@Laboulbeniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Laboulbeniales', 1),
(@Laboulbeniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pyxidiophorales', 1),
(@Lichinomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Lichinales', 1),
(@Acarosporomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Acarosporales', 1),
(@Lecanoromycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Candelariales', 1),
(@Lecanoromycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Umbilicariales', 1),
(@Lecanoromycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Lecanorales', 1),
(@Lecanoromycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Peltigerales', 1),
(@Lecanoromycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Teloschistales', 1);


SET @Ostropomycetidae_id = (SELECT id FROM Taxons WHERE nome='Ostropomycetidae');
SET @Leotiomycetes_id = (SELECT id FROM Taxons WHERE nome='Leotiomycetes');

INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Ostropomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Agyriales', 1),
(@Ostropomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Baeomycetales', 1),
(@Ostropomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Ostropales', 1),
(@Ostropomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pertusariales', 1),
(@Leotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Cyttariales', 1),
(@Leotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Erysiphales', 1),
(@Leotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Helotiales', 1),
(@Leotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Rhytismatales', 1),
(@Leotiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Thelebolales', 1);

SET @Sordariomycetes_id = (SELECT id FROM Taxons WHERE nome='Sordariomycetes');
SET @Xylariomycetidae_id = (SELECT id FROM Taxons WHERE nome='Xylariomycetidae');
SET @Hypocreomycetidae_id = (SELECT id FROM Taxons WHERE nome='Hypocreomycetidae');
SET @Sordariomycetidae_id = (SELECT id FROM Taxons WHERE nome='Sordariomycetidae');

INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Calosphaeriales', 1),
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Lulworthiales', 1),
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Meliolales', 1),
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Phyllachorales', 1),
(@Sordariomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Trichosphaeriales', 1),
(@Xylariomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Xylariales', 1),

(@Hypocreomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Coronophorales', 1),
(@Hypocreomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Hypocreales', 1),
(@Hypocreomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Macroasporales', 1),
(@Hypocreomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Melanosporales', 1),

(@Sordariomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Boliniales', 1),
(@Sordariomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Chaetosphaeriales', 1),
(@Sordariomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Coniochaetales', 1),
(@Sordariomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Diaporthales', 1),
(@Sordariomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Ophiostomatales', 1),
(@Sordariomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Sordariales', 1);


-- classes Basiciomycota
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Basidiomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Wallemiomycetes', 1);

SET @Pucciniomycotina_id = (SELECT id FROM Taxons WHERE nome='Basidiomycota');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Classiculomycetes', 1),
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Cryptomycocolacomycetes', 1),
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Mixiomycetes', 1),
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Atractiellomycetes', 1),
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Agaricostillbomycetes', 1),
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Cystobasidiomycetes', 1),
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Pucciniomycetes', 1),
(@Pucciniomycotina_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Microbotryomycetes', 1);

SET @Ustilaginomycota_id = (SELECT id FROM Taxons WHERE nome='Basidiomycota');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Ustilaginomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Ustilaginomycetes', 1),
(@Ustilaginomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Exobasidiomycetes', 1);

SET @Agaricomycotina_id = (SELECT id FROM Taxons WHERE nome='Agaricomycotina');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Ustilaginomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Tremellomycetes', 1),
(@Ustilaginomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Dacrymycetes', 1),
(@Ustilaginomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Classe'), 'Agaricomycetes', 1);


-- subclasses basidiomycota

SET @Agaricomycetes_id = (SELECT id FROM Taxons WHERE nome='Agaricomycetes');
INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Phallomycetidae', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Subclasse'), 'Agaricomycetidae', 1);


-- ordens basidiomycota

SET @Wallemiomycetes_id = (SELECT id FROM Taxons WHERE nome='Wallemiomycetes');
SET @Classiculomycetes_id = (SELECT id FROM Taxons WHERE nome='Classiculomycetes');
SET @Cryptomycocolacomycetes_id = (SELECT id FROM Taxons WHERE nome='Cryptomycocolacomycetes');
SET @Mixiomycetes_id = (SELECT id FROM Taxons WHERE nome='Mixiomycetes');
SET @Atractiellomycetes_id = (SELECT id FROM Taxons WHERE nome='Atractiellomycetes');
SET @Agaricostillbomycetes_id = (SELECT id FROM Taxons WHERE nome='Agaricostillbomycetes');
SET @Cystobasidiomycetes_id = (SELECT id FROM Taxons WHERE nome='Cystobasidiomycetes');
SET @Pucciniomycetes_id = (SELECT id FROM Taxons WHERE nome='Pucciniomycetes');
SET @Microbotryomycetes_id = (SELECT id FROM Taxons WHERE nome='Microbotryomycetes');
SET @Ustilaginomycetes_id = (SELECT id FROM Taxons WHERE nome='Ustilaginomycetes');
SET @Exobasidiomycetes_id = (SELECT id FROM Taxons WHERE nome='Exobasidiomycetes');
SET @Tremellomycetes_id = (SELECT id FROM Taxons WHERE nome='Tremellomycetes');
SET @Dacrymycetes_id = (SELECT id FROM Taxons WHERE nome='Dacrymycetes');
SET @Agaricomycetes_id = (SELECT id FROM Taxons WHERE nome='Agaricomycetes');
SET @Phallomycetidae_id = (SELECT id FROM Taxons WHERE nome='Phallomycetidae');
SET @Agaricomycetidae_id = (SELECT id FROM Taxons WHERE nome='Agaricomycetidae');

INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Ustilaginomycota_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Malasseziales', 1),
(@Wallemiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Wallemiales', 1);

INSERT INTO Taxons (taxonanterior_id, unidadesTaxonomicas_id, nome, autor_id) VALUES
(@Classiculomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Classiculales', 1),
(@Cryptomycocolacomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Cryptomycocolacales', 1),
(@Mixiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Mixiales', 1),
(@Atractiellomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Atractiellales', 1),
(@Agaricostillbomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Spiculogloeales', 1),
(@Agaricostillbomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Agaricostillbales', 1),
(@Cystobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Cytobasidiales', 1),
(@Cystobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Erythrobasidiales', 1),
(@Cystobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Naohideales', 1),
(@Pucciniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Helicobasidiales', 1),
(@Pucciniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Platygloeales', 1),
(@Pucciniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Septobasidiales', 1),
(@Pucciniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pucciniales', 1),
(@Pucciniomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Pachnocybales', 1),
(@Microbotryomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Heterogastridiales', 1),
(@Microbotryomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Leucosporidiales', 1),
(@Microbotryomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Microbortyales', 1),
(@Microbotryomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Sporidiobolales', 1),
(@Ustilaginomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Urocystales', 1),
(@Ustilaginomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Ustilaginales', 1),
(@Exobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Doassansiales', 1),
(@Exobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Entylomatales', 1),
(@Exobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Exobasidiales', 1),
(@Exobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Georgefischeriales', 1),
(@Exobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Microstromatales', 1),
(@Exobasidiomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Tilletiales', 1),
(@Tremellomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Cystofilobasidiales', 1),
(@Tremellomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Filobasidiales', 1),
(@Tremellomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Tremellales', 1),
(@Dacrymycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Dacrymycetales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Auriculariales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Sebacinales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Cantharellales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Trechisporales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Hymenochaestales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Corticiales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Gloeophyllales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Polyporales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Theleophorales', 1),
(@Agaricomycetes_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Russulales', 1),
(@Phallomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Geastrales', 1),
(@Phallomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Gomphales', 1),
(@Phallomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Hysterangiales', 1),
(@Phallomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Phallales', 1),
(@Agaricomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Agaricales', 1),
(@Agaricomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Atheliales', 1),
(@Agaricomycetidae_id, (SELECT id FROM UnidadesTaxonomicas WHERE nome='Ordem'), 'Boletales', 1);

-- users padrão

INSERT INTO Autores (nome) VALUES 
('ZATTA, F. B.'),
('ZATTA, L. B.');
INSERT INTO Usuarios (nome, sobrenome, ultimonome, email, senha, autor_id, permissoes) VALUES 
('Filipe', 'Backes', 'Zatta', 'filipe.fbz@gmail.com', 'senha123', 2, 'admin'),
('Luiza', 'Backes', 'Zatta', 'luiza.lbz@gmail.com', 'senha123', 3, 'admin');

